//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTimeTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTimeTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Clock_16 {
            get {
                object obj = ResourceManager.GetObject("Clock_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Clock_48 {
            get {
                object obj = ResourceManager.GetObject("Clock_48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyTimeTrackerData.xml.
        /// </summary>
        internal static string DefaultFilename {
            get {
                return ResourceManager.GetString("DefaultFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Hourglass_16 {
            get {
                object obj = ResourceManager.GetObject("Hourglass_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentTask.
        /// </summary>
        internal static string RegKey_CurrentTask {
            get {
                return ResourceManager.GetString("RegKey_CurrentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFilename.
        /// </summary>
        internal static string RegKey_DataFilename {
            get {
                return ResourceManager.GetString("RegKey_DataFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Start_16 {
            get {
                object obj = ResourceManager.GetObject("Start_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Stop_16 {
            get {
                object obj = ResourceManager.GetObject("Stop_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categoryName.
        /// </summary>
        internal static string XMLAttribute_Category {
            get {
                return ResourceManager.GetString("XMLAttribute_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectName.
        /// </summary>
        internal static string XMLAttribute_Project {
            get {
                return ResourceManager.GetString("XMLAttribute_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to taskName.
        /// </summary>
        internal static string XMLAttribute_Task {
            get {
                return ResourceManager.GetString("XMLAttribute_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories.
        /// </summary>
        internal static string XMLNodeGroup_Categories {
            get {
                return ResourceManager.GetString("XMLNodeGroup_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        internal static string XMLNodeGroup_Projects {
            get {
                return ResourceManager.GetString("XMLNodeGroup_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tasks.
        /// </summary>
        internal static string XMLNodeGroup_Tasks {
            get {
                return ResourceManager.GetString("XMLNodeGroup_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeEntries.
        /// </summary>
        internal static string XMLNodeGroup_TimeEntries {
            get {
                return ResourceManager.GetString("XMLNodeGroup_TimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        internal static string XMLNodeName_Category {
            get {
                return ResourceManager.GetString("XMLNodeName_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project.
        /// </summary>
        internal static string XMLNodeName_Project {
            get {
                return ResourceManager.GetString("XMLNodeName_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        internal static string XMLNodeName_Task {
            get {
                return ResourceManager.GetString("XMLNodeName_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeEntry.
        /// </summary>
        internal static string XMLNodeName_TimeEntry {
            get {
                return ResourceManager.GetString("XMLNodeName_TimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeCard.
        /// </summary>
        internal static string XMLRootNode {
            get {
                return ResourceManager.GetString("XMLRootNode", resourceCulture);
            }
        }
    }
}
